name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run migrations & optimize (via SSH)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.REMOTE_PATH }}
            git pull origin develop
            /opt/php84/bin/php /usr/local/bin/composer install --no-dev --optimize-autoloader
            /opt/php84/bin/php artisan cache:clear
            /opt/php84/bin/php artisan config:clear
            /opt/php84/bin/php artisan route:trans:cache
            /opt/php84/bin/php artisan view:clear
            /opt/php84/bin/php artisan config:cache
            /opt/php84/bin/php artisan route:trans:clear
            /opt/php84/bin/php artisan view:cache
            /opt/php84/bin/php artisan migrate --force
            npm install
            npm run build
